name: sunny_dart
version: 0.6.0+4
homepage: https://github.com/SunnyApp/sunny_dart
description: Core utilities used by sunny packages
environment: 
  sdk: '>=2.8.0 <3.0.0'
dependencies: 
  async: ^2.9.0
  chunked_stream: ^1.2.0
  collection: ^1.16.0
  crypto: ^3.0.2
  equatable: ^2.0.5
  inflection2: ^0.4.3
  meta: ^1.8.0
  intl: ^0.17.0
  libphonenumber: ^1.0.2
  logging: ^1.0.2
  pedantic: ^1.11.1
  platform_detect: ^1.4.0
  recase: ^4.0.0
  stream_transform: ^2.0.0
  timezone: ^0.9.0
  uuid: ^3.0.6
  uri: 
    path: /Users/ericm/sunny/local_plugins/uri.dart
  flutter: 
    sdk: flutter
dev_dependencies: 
  logging_config: 
    path: /Users/ericm/reliveit/checkout/SunnyApp/logging_config
  flutter_test: 
    sdk: flutter
