name: sunny_dart
description: Core utilities used by sunny packages
version: 0.4.4
homepage: https://github.com/SunnyApp/sunny_dart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter_native_timezone: any
  inflection2: any
  intl: any
  equatable: any
  logging: ^0.11.4
  devicelocale: ^0.2.2
  libphonenumber: ^1.0.1
  recase: ^3.0.0
  stream_transform: ^1.2.0
  timezone: ^0.5.6
  platform_detect: ^1.4.0
  device_info: ^0.4.2+1
  uri: ^0.11.3+1
  uuid: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
