name: sunny_dart
version: 0.7.0+4
homepage: https://github.com/SunnyApp/sunny_dart
description: Core utilities used by sunny packages
environment: 
  sdk: '>=2.8.0 <3.0.0'
dependencies: 
  async: ^2.5.0
  chunked_stream: ^1.4.0
  collection: ^1.15.0
  crypto: ^3.0.0
  equatable: ^2.0.0
  inflection2: ^0.4.3
  meta: ^1.3.0
  intl: ^0.17.0
  libphonenumber: ^1.0.2
  logging: ^1.0.0
  pedantic: ^1.11.0
  platform_detect: ^1.4.0
  recase: ^3.0.1
  stream_transform: ^2.0.0
  timezone: ^0.6.1
  uri: ^1.0.0
  uuid: ^3.0.1
  flutter: 
    sdk: flutter
dev_dependencies: 
  logging_config: ^0.5.7+2
  flutter_test: 
    sdk: flutter
