name: sunny_dart
version: 0.11.0+5
homepage: https://github.com/SunnyApp/sunny_dart
description: Core utilities used by sunny packages
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  async: ^2.5.0
  chunked_stream: ^1.4.1
  collection: ^1.15.0
  crypto: ^3.0.1
  dartxx: ^0.5.3+2
  equatable: ^2.0.0
  flexidate: ^0.6.0+2
  inflection3: ^0.5.3+2
  info_x: ^0.7.0+1
  intl: ^0.17.0
  libphonenumber2: ^2.0.2+2
  logging: ^1.0.1
  meta: ^1.3.0
  pedantic: ^1.11.0
  platform_detect2: ^1.5.0+2
  recase: ^4.0.0
  stream_transform: ^2.0.0
  timezone: ^0.7.0
  uri: ^1.0.0
  uuid: ^3.0.4
dev_dependencies: 
  flutter_test: 
    sdk: flutter
